export const mockPhoneNumbers = [
  {
    phone_number: "+19787836427",
    location: "Massachusetts",
    type: "Voice",
    status: "Active",
    monthly_cost: 1.0,
    capabilities: ["voice", "sms"],
    date_purchased: "2023-04-15T10:30:00Z",
  },
  {
    phone_number: "+14155552671",
    location: "California",
    type: "Voice",
    status: "Active",
    monthly_cost: 1.0,
    capabilities: ["voice", "sms"],
    date_purchased: "2023-05-20T14:45:00Z",
  },
  {
    phone_number: "+12125557890",
    location: "New York",
    type: "Voice",
    status: "Active",
    monthly_cost: 1.0,
    capabilities: ["voice"],
    date_purchased: "2023-06-10T09:15:00Z",
  },
  {
    phone_number: "+13125559012",
    location: "Illinois",
    type: "Voice",
    status: "Available",
    monthly_cost: 1.0,
    capabilities: ["voice", "sms"],
    date_purchased: null,
  },
  {
    phone_number: "+17705551234",
    location: "Georgia",
    type: "Voice",
    status: "Available",
    monthly_cost: 1.0,
    capabilities: ["voice", "sms"],
    date_purchased: null,
  },
]
